from __future__ import annotations

import json
from pathlib import Path


def write_resolve_render_timeline_script(path: Path, payload: dict) -> None:
    payload_json = json.dumps(payload)
    script = """# Auto-generated by VideoAssistant
# Render a timeline to a single file (DaVinci Resolve scripting)
#
# Requirements:
# - DaVinci Resolve must be running (or launched with -nogui).
# - External Python must be able to import DaVinciResolveScript.

import json
import os
import sys
import time

PAYLOAD = json.loads(r'''""" + payload_json + r"""''')


def add_resolve_modules_to_syspath():
    candidates = []
    for env_key in ['RESOLVE_SCRIPTING_MODULES', 'RESOLVE_SCRIPT_API']:
        env = os.environ.get(env_key)
        if env:
            candidates.append(env)
    candidates.extend([
        r"C:\\ProgramData\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
        r"C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
    ])
    for p in candidates:
        if p and os.path.isdir(p) and p not in sys.path:
            sys.path.insert(0, p)


def get_resolve():
    add_resolve_modules_to_syspath()
    try:
        import DaVinciResolveScript as dvr
    except Exception as e:
        raise SystemExit('Cannot import DaVinciResolveScript: ' + str(e))

    # Resolve may take a bit to start; retry for a short window.
    deadline_s = int(PAYLOAD.get('connect_timeout_s') or 30)
    for _ in range(max(1, deadline_s)):
        resolve = dvr.scriptapp('Resolve')
        if resolve is not None:
            return resolve
        time.sleep(1)

    raise SystemExit(
        'Resolve scripting app not available after waiting. '\
        'Start Resolve (same user/admin level as this terminal), '\
        'enable Preferences > System > General > External scripting, '\
        'and re-run.'
    )


def find_timeline_by_name(proj, name: str):
    try:
        count = int(proj.GetTimelineCount())
    except Exception:
        return None
    for i in range(1, count + 1):
        tl = proj.GetTimelineByIndex(i)
        if tl and tl.GetName() == name:
            return tl
    return None


def pick_format_codec(project):
    try:
        formats = project.GetRenderFormats() or {}
    except Exception:
        formats = {}

    formats_lc = {str(k).lower(): k for k in formats.keys()}

    def pick_codec_for(fmt_key: str):
        try:
            codecs = project.GetRenderCodecs(fmt_key) or {}
        except Exception:
            codecs = {}

        def find(pred):
            for desc, name in codecs.items():
                d = (desc or '').lower()
                n = (name or '').lower()
                if pred(d) or pred(n):
                    return name
            return None

        # Prefer NVIDIA encoders when available.
        c = find(lambda s: ('265' in s or 'hevc' in s or 'h.265' in s) and ('nvidia' in s))
        if c:
            return c
        c = find(lambda s: ('265' in s or 'hevc' in s or 'h.265' in s))
        if c:
            return c
        c = find(lambda s: ('264' in s or 'avc' in s or 'h.264' in s) and ('nvidia' in s))
        if c:
            return c
        c = find(lambda s: ('264' in s or 'avc' in s or 'h.264' in s))
        if c:
            return c

        for _, name in codecs.items():
            return name
        return None

    for fmt_lc in ['mp4', 'mkv', 'quicktime']:
        fmt_key = formats_lc.get(fmt_lc)
        if fmt_key:
            c = pick_codec_for(fmt_key)
            if c:
                return fmt_key, c

    for fmt in formats.keys():
        c = pick_codec_for(fmt)
        if c:
            return fmt, c

    return None, None


def wait_for_render(project):
    while True:
        try:
            if not project.IsRenderingInProgress():
                return
        except Exception:
            return
        time.sleep(1)


def newest_matching_file(target_dir: str, custom_name: str):
    try:
        names = os.listdir(target_dir)
    except Exception:
        return None

    cn = (custom_name or '').lower()
    matches = []
    for n in names:
        p = os.path.join(target_dir, n)
        if not os.path.isfile(p):
            continue
        stem, _ext = os.path.splitext(n)
        s = (stem or '').lower()
        if s == cn or s.startswith(cn) or (cn and cn in s):
            try:
                matches.append((os.path.getmtime(p), p))
            except Exception:
                pass
    if not matches:
        return None
    matches.sort(key=lambda x: x[0], reverse=True)
    return matches[0][1]


def main():
    resolve = get_resolve()
    pm = resolve.GetProjectManager()
    proj = pm.LoadProject(PAYLOAD['project_name'])
    if not proj:
        try:
            proj = pm.GetCurrentProject()
        except Exception:
            proj = None
    if not proj:
        raise SystemExit('Project not loaded: ' + PAYLOAD['project_name'])

    tl = find_timeline_by_name(proj, PAYLOAD['timeline_name'])
    if not tl:
        raise SystemExit('Timeline not found: ' + PAYLOAD['timeline_name'])
    proj.SetCurrentTimeline(tl)

    resolve.OpenPage('deliver')
    preset = PAYLOAD.get('render_preset')
    if preset:
        try:
            proj.LoadRenderPreset(preset)
        except Exception:
            pass

    fmt = PAYLOAD.get('render_format')
    cdc = PAYLOAD.get('render_codec')
    if not (fmt and cdc):
        fmt, cdc = pick_format_codec(proj)
    if fmt and cdc:
        try:
            proj.SetCurrentRenderFormatAndCodec(fmt, cdc)
        except Exception:
            pass

    # Single clip render.
    try:
        proj.SetCurrentRenderMode(1)
    except Exception:
        pass

    target_dir = PAYLOAD['target_dir']
    os.makedirs(target_dir, exist_ok=True)
    custom_name = PAYLOAD.get('custom_name') or PAYLOAD['timeline_name']

    proj.SetRenderSettings({
        'TargetDir': target_dir,
        'CustomName': custom_name,
        'SelectAllFrames': 1,
        'ExportVideo': 1,
        'ExportAudio': 1,
        'NetworkOptimization': 1,
        'ReplaceExistingFilesInPlace': 1,
    })

    job_id = proj.AddRenderJob()
    if not job_id:
        raise SystemExit('Failed to add render job')

    proj.StartRendering([job_id])
    wait_for_render(proj)

    out_file = newest_matching_file(target_dir, custom_name)
    if out_file:
        print('OUTPUT_FILE=' + out_file)
    else:
        print('OUTPUT_DIR=' + target_dir)

    try:
        proj.DeleteAllRenderJobs()
    except Exception:
        pass
    try:
        pm.SaveProject()
    except Exception:
        pass


if __name__ == '__main__':
    main()
"""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(script, encoding="utf-8")
