from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path
import sys

from videoassistant.agents.base import AgentContext, AgentResult


def _write_resolve_correction_script(path: Path, payload: dict) -> None:
    payload_json = json.dumps(payload)
    script = """# Auto-generated by VideoAssistant
# Apply grade/LUT to *_SELECTS timelines

import json
import os
import sys

PAYLOAD = json.loads(r'''""" + payload_json + r"""''')


def add_resolve_modules_to_syspath():
    candidates = []
    for env_key in ['RESOLVE_SCRIPTING_MODULES', 'RESOLVE_SCRIPT_API']:
        env = os.environ.get(env_key)
        if env:
            candidates.append(env)
    candidates.extend([
        r"C:\\ProgramData\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
        r"C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
    ])
    for p in candidates:
        if p and os.path.isdir(p) and p not in sys.path:
            sys.path.insert(0, p)


def get_resolve():
    add_resolve_modules_to_syspath()
    try:
        import DaVinciResolveScript as dvr
    except Exception as e:
        raise SystemExit('Cannot import DaVinciResolveScript: ' + str(e))
    resolve = dvr.scriptapp('Resolve')
    if resolve is None:
        raise SystemExit('Resolve scripting app not available. Start Resolve and re-run.')
    return resolve


def main():
    resolve = get_resolve()
    pm = resolve.GetProjectManager()
    proj = pm.LoadProject(PAYLOAD['project_name'])
    if not proj:
        try:
            proj = pm.GetCurrentProject()
        except Exception:
            proj = None
    if not proj:
        raise SystemExit('Project not loaded: ' + PAYLOAD['project_name'])

    drx = PAYLOAD.get('drx_path')
    lut = PAYLOAD.get('lut_path')
    grade_mode = int(PAYLOAD.get('grade_mode', 0))
    auto_grade = bool(PAYLOAD.get('auto_grade', True))
    cdl = PAYLOAD.get('cdl') or {}

    # Apply grade to generated selects timelines.
    suffixes = PAYLOAD.get('timeline_suffixes') or []
    legacy_suffix = PAYLOAD.get('timeline_suffix')
    if legacy_suffix:
        suffixes = list(suffixes) + [legacy_suffix]
    if not suffixes:
        suffixes = ['_SELECTS', '_SELECTS_CINE']
    try:
        count = int(proj.GetTimelineCount())
    except Exception:
        count = 0

    corrected_timelines = 0
    cdl_applied_items = 0
    lut_applied_items = 0
    drx_applied_timelines = 0
    for i in range(1, count + 1):
        tl = proj.GetTimelineByIndex(i)
        if not tl:
            continue
        name = tl.GetName() or ''
        if suffixes and (not any(name.endswith(s) for s in suffixes)):
            continue

        timeline_corrected = False

        # Apply DRX grade to all clips in timeline (video tracks).
        if drx:
            try:
                track_count = int(tl.GetTrackCount('video'))
            except Exception:
                track_count = 0
            ok = True
            for t in range(1, track_count + 1):
                clips = tl.GetItemListInTrack('video', t) or []
                if clips:
                    if not tl.ApplyGradeFromDRX(drx, grade_mode, clips):
                        ok = False
                        break
            if ok:
                drx_applied_timelines += 1
                timeline_corrected = True

        # Optional LUT on node graph of each timeline item.
        if lut:
            try:
                track_count = int(tl.GetTrackCount('video'))
            except Exception:
                track_count = 0
            for t in range(1, track_count + 1):
                clips = tl.GetItemListInTrack('video', t) or []
                for it in clips:
                    try:
                        g = it.GetNodeGraph()
                        if g:
                            g.SetLUT(1, lut)
                            lut_applied_items += 1
                            timeline_corrected = True
                    except Exception:
                        pass

        # Auto grade via CDL (subtle contrast/sat polish).
        if auto_grade:
            try:
                track_count = int(tl.GetTrackCount('video'))
            except Exception:
                track_count = 0
            for t in range(1, track_count + 1):
                clips = tl.GetItemListInTrack('video', t) or []
                for it in clips:
                    try:
                        ok = it.SetCDL({
                            'NodeIndex': '1',
                            'Slope': cdl.get('slope', '1.02 1.02 1.02'),
                            'Offset': cdl.get('offset', '0.0 0.0 0.0'),
                            'Power': cdl.get('power', '0.98 0.98 0.98'),
                            'Saturation': cdl.get('saturation', '1.08'),
                        })
                        if ok:
                            cdl_applied_items += 1
                            timeline_corrected = True
                    except Exception:
                        pass

        print('Corrected timeline: ' + name)

        if timeline_corrected:
            corrected_timelines += 1

    print(f'Done. Corrected timelines: {corrected_timelines}')
    print(f'Details: DRX timelines={drx_applied_timelines}, LUT items={lut_applied_items}, CDL items={cdl_applied_items}')


if __name__ == '__main__':
    main()
"""

    path.write_text(script, encoding="utf-8")


@dataclass
class CorrectionAgent:
    name: str = "correction"

    def run(self, ctx: AgentContext) -> AgentResult:
        # Correction targets *_SELECTS timelines created by the Resolve import step.
        # If that step was not requested, skip gracefully instead of failing on an
        # unloaded/non-existent Resolve project.
        if not bool(getattr(ctx, "run_resolve_import", False)):
            return AgentResult(name=self.name, ok=True, summary="Skipped correction (Resolve import not requested)")

        # If we're baking grades into exported pretrim clips, avoid double-grading *_SELECTS timelines.
        if ctx.export_pretrim and ctx.skip_timeline_correction_if_pretrim:
            return AgentResult(name=self.name, ok=True, summary="Skipped timeline correction (grade baked into pretrim exports)")

        # Always apply the auto-grade baseline unless disabled.
        if not ctx.auto_grade and (not ctx.grade_drx_path) and (not ctx.grade_lut_path):
            return AgentResult(name=self.name, ok=True, summary="Skipped correction")

        script_path = ctx.va_dir / "resolve_apply_correction.py"
        payload = {
            "project_name": ctx.project_name,
            "drx_path": str(ctx.grade_drx_path) if ctx.grade_drx_path else None,
            "grade_mode": int(ctx.grade_mode),
            "lut_path": ctx.grade_lut_path,
            "auto_grade": bool(ctx.auto_grade),
            "cdl": {
                "slope": ctx.cdl_slope,
                "offset": ctx.cdl_offset,
                "power": ctx.cdl_power,
                "saturation": ctx.cdl_saturation,
            },
            "timeline_suffixes": ["_SELECTS", "_SELECTS_CINE"],
        }
        _write_resolve_correction_script(script_path, payload)

        proc = subprocess.run([sys.executable, str(script_path)], capture_output=True, text=True)
        if proc.returncode != 0:
            return AgentResult(
                name=self.name,
                ok=False,
                summary=f"Resolve correction script failed (exit={proc.returncode}).\n{proc.stderr.strip()}",
                artifacts={"correction_script": str(script_path)},
            )

        warnings = []
        if proc.stderr.strip():
            warnings.append(proc.stderr.strip())
        if proc.stdout.strip():
            warnings.append(proc.stdout.strip())

        return AgentResult(
            name=self.name,
            ok=True,
            summary="Applied correction to *_SELECTS timelines",
            artifacts={"correction_script": str(script_path), "stdout": proc.stdout.strip()},
            warnings=warnings,
        )
