from __future__ import annotations

import json
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
import sys

from videoassistant.agents.base import AgentContext, AgentResult, read_json, write_json


def _safe_prefix(template: str, *, room: str, project: str) -> str:
    try:
        s = template.format(room=room, project=project)
    except Exception:
        s = template
    # Avoid path separators and other awkward chars.
    s = s.replace("/", "_").replace("\\", "_").replace(":", "_")
    return s


def _find_rendered_file(dir_path: Path, source_stem: str) -> Path | None:
    if not dir_path.exists():
        return None
    stem = source_stem.lower()
    matches: list[Path] = []
    for p in dir_path.glob("*"):
        if not p.is_file():
            continue
        cand = p.stem.lower()
        if cand == stem or cand.startswith(stem) or (stem in cand):
            matches.append(p)
    if not matches:
        return None
    matches.sort(key=lambda x: x.stat().st_mtime, reverse=True)
    return matches[0]


def _unique_path(dir_path: Path, base_name: str, suffix: str) -> Path:
    p = dir_path / f"{base_name}{suffix}"
    if not p.exists():
        return p
    for i in range(2, 10_000):
        cand = dir_path / f"{base_name}_{i}{suffix}"
        if not cand.exists():
            return cand
    return p


def _write_resolve_pretrim_export_script(path: Path, payload: dict) -> None:
    payload_json = json.dumps(payload)
    script = """# Auto-generated by VideoAssistant
# Export FULL selected clips (stabilized + graded) before autotrim.

import json
import os
import sys
import time

PAYLOAD = json.loads(r'''""" + payload_json + r"""''')


def add_resolve_modules_to_syspath():
    candidates = []
    for env_key in ['RESOLVE_SCRIPTING_MODULES', 'RESOLVE_SCRIPT_API']:
        env = os.environ.get(env_key)
        if env:
            candidates.append(env)
    candidates.extend([
        r"C:\\ProgramData\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
        r"C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
    ])
    for p in candidates:
        if p and os.path.isdir(p) and p not in sys.path:
            sys.path.insert(0, p)


def get_resolve():
    add_resolve_modules_to_syspath()
    try:
        import DaVinciResolveScript as dvr
    except Exception as e:
        raise SystemExit('Cannot import DaVinciResolveScript: ' + str(e))
    resolve = dvr.scriptapp('Resolve')
    if resolve is None:
        raise SystemExit('Resolve scripting app not available. Start Resolve and re-run.')
    return resolve


def find_timeline_by_name(proj, name: str):
    try:
        count = int(proj.GetTimelineCount())
    except Exception:
        return None
    for i in range(1, count + 1):
        tl = proj.GetTimelineByIndex(i)
        if tl and tl.GetName() == name:
            return tl
    return None


def ensure_unique_timeline(proj, media_pool, base_name: str):
    name = base_name
    i = 2
    while find_timeline_by_name(proj, name):
        name = f"{base_name}_{i}"
        i += 1
    try:
        tl = media_pool.CreateEmptyTimeline(name)
    except Exception:
        tl = None
    return tl or find_timeline_by_name(proj, name)


def ensure_project(pm, project_name: str):
    proj = pm.LoadProject(project_name)
    if proj:
        return proj
    proj = pm.CreateProject(project_name)
    if not proj:
        raise SystemExit('Failed to create project: ' + project_name)
    return proj


def ensure_bin(media_pool, parent, name: str):
    for b in parent.GetSubFolderList() or []:
        if b.GetName() == name:
            return b
    return media_pool.AddSubFolder(parent, name)


def pick_format_codec(project):
    try:
        formats = project.GetRenderFormats() or {}
    except Exception:
        formats = {}

    formats_lc = {str(k).lower(): k for k in formats.keys()}

    def pick_codec_for(fmt_key: str):
        try:
            codecs = project.GetRenderCodecs(fmt_key) or {}
        except Exception:
            codecs = {}

        def find(pred):
            for desc, name in codecs.items():
                d = (desc or '').lower()
                n = (name or '').lower()
                if pred(d) or pred(n):
                    return name
            return None

        c = find(lambda s: ('265' in s or 'hevc' in s or 'h.265' in s) and ('nvidia' in s))
        if c:
            return c
        c = find(lambda s: ('265' in s or 'hevc' in s or 'h.265' in s))
        if c:
            return c
        c = find(lambda s: ('264' in s or 'avc' in s or 'h.264' in s) and ('nvidia' in s))
        if c:
            return c
        c = find(lambda s: ('264' in s or 'avc' in s or 'h.264' in s))
        if c:
            return c
        for _, name in codecs.items():
            return name
        return None

    for fmt_lc in ['mp4', 'mkv', 'quicktime']:
        fmt_key = formats_lc.get(fmt_lc)
        if fmt_key:
            c = pick_codec_for(fmt_key)
            if c:
                return fmt_key, c

    for fmt in formats.keys():
        c = pick_codec_for(fmt)
        if c:
            return fmt, c
    return None, None


def apply_grade_to_timeline_items(timeline, drx: str | None, grade_mode: int, lut: str | None, auto_grade: bool, cdl: dict):
    # Apply DRX at timeline-level using provided clip list.
    if drx:
        try:
            track_count = int(timeline.GetTrackCount('video'))
        except Exception:
            track_count = 0
        for t in range(1, track_count + 1):
            clips = timeline.GetItemListInTrack('video', t) or []
            if clips:
                try:
                    timeline.ApplyGradeFromDRX(drx, int(grade_mode), clips)
                except Exception:
                    pass

    # Per-item LUT and/or CDL.
    try:
        track_count = int(timeline.GetTrackCount('video'))
    except Exception:
        track_count = 0
    for t in range(1, track_count + 1):
        clips = timeline.GetItemListInTrack('video', t) or []
        for it in clips:
            if lut:
                try:
                    g = it.GetNodeGraph()
                    if g:
                        g.SetLUT(1, lut)
                except Exception:
                    pass
            if auto_grade:
                try:
                    it.SetCDL({
                        'NodeIndex': '1',
                        'Slope': cdl.get('slope', '1.02 1.02 1.02'),
                        'Offset': cdl.get('offset', '0.0 0.0 0.0'),
                        'Power': cdl.get('power', '0.98 0.98 0.98'),
                        'Saturation': cdl.get('saturation', '1.08'),
                    })
                except Exception:
                    pass


def wait_for_render(project):
    while True:
        try:
            if not project.IsRenderingInProgress():
                return
        except Exception:
            return
        time.sleep(1)


def main():
    resolve = get_resolve()
    pm = resolve.GetProjectManager()
    proj = ensure_project(pm, PAYLOAD['project_name'])
    media_pool = proj.GetMediaPool()
    root_folder = media_pool.GetRootFolder()

    room_bins = {}
    for room in sorted(PAYLOAD['rooms'].keys()):
        room_bins[room] = ensure_bin(media_pool, root_folder, room)

    drx = PAYLOAD.get('drx_path')
    lut = PAYLOAD.get('lut_path')
    grade_mode = int(PAYLOAD.get('grade_mode', 0))
    auto_grade = bool(PAYLOAD.get('auto_grade', True))
    cdl = PAYLOAD.get('cdl') or {}

    render_jobs = []
    for room in sorted(PAYLOAD['rooms'].keys()):
        clip_paths = PAYLOAD['rooms'][room]
        if not clip_paths:
            continue
        out_dir = PAYLOAD['out_dir_by_room'][room]
        os.makedirs(out_dir, exist_ok=True)

        # Import clips into a room bin.
        media_pool.SetCurrentFolder(room_bins[room])
        items = []
        for clip_path in clip_paths:
            imported = media_pool.ImportMedia([clip_path])
            if imported:
                items.append(imported[0])

        # Put full clips onto a temp timeline so grades are applied and can be rendered.
        tl = ensure_unique_timeline(proj, media_pool, room.upper() + '_PRETRIM_EXPORT')
        if not tl:
            continue
        proj.SetCurrentTimeline(tl)
        if items:
            try:
                media_pool.AppendToTimeline(items)
            except Exception:
                pass

        # Apply grade/LUT/CDL.
        resolve.OpenPage('edit')
        apply_grade_to_timeline_items(tl, drx, grade_mode, lut, auto_grade, cdl)

        # Render individual clips.
        resolve.OpenPage('deliver')
        preset = PAYLOAD.get('render_preset')
        if preset:
            try:
                proj.LoadRenderPreset(preset)
            except Exception:
                pass

        fmt = PAYLOAD.get('render_format')
        cdc = PAYLOAD.get('render_codec')
        if not (fmt and cdc):
            fmt, cdc = pick_format_codec(proj)
        if fmt and cdc:
            try:
                proj.SetCurrentRenderFormatAndCodec(fmt, cdc)
            except Exception:
                pass

        try:
            proj.SetCurrentRenderMode(0)  # individual clips
        except Exception:
            pass

        proj.SetRenderSettings({
            'TargetDir': out_dir,
            'SelectAllFrames': 1,
            'ExportVideo': 1,
            'ExportAudio': 1,
            'NetworkOptimization': 1,
            'ReplaceExistingFilesInPlace': 1,
        })

        job_id = proj.AddRenderJob()
        if job_id:
            render_jobs.append(job_id)

    if not render_jobs:
        print('No render jobs created.')
        return

    proj.StartRendering(render_jobs)
    wait_for_render(proj)
    try:
        proj.DeleteAllRenderJobs()
    except Exception:
        pass
    try:
        pm.SaveProject()
    except Exception:
        pass
    print('Done. Exported pretrim graded clips per room.')


if __name__ == '__main__':
    main()
"""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(script, encoding="utf-8")


@dataclass
class PretrimExportAgent:
    name: str = "pretrim_export"

    def run(self, ctx: AgentContext) -> AgentResult:
        if not ctx.export_pretrim:
            return AgentResult(name=self.name, ok=True, summary="Skipped pretrim export")

        index_path = ctx.va_dir / "index.json"
        selects_path = ctx.va_dir / "selects.json"
        if not index_path.exists() or not selects_path.exists():
            return AgentResult(name=self.name, ok=False, summary="Missing index/selects; run earlier agents first")

        index = read_json(index_path)
        selects = read_json(selects_path)

        selected_rels: set[str] = set()
        for rel, info in (selects.get("clips") or {}).items():
            if info.get("error"):
                continue
            segs = info.get("segments") or []
            if segs:
                selected_rels.add(rel)

        if not selected_rels:
            return AgentResult(name=self.name, ok=True, summary="No selected clips found; nothing to export")

        clips = index.get("clips") or []
        clips_by_rel = {c.get("rel"): c for c in clips if c.get("rel")}

        # Build room -> list of *current* clip paths (stabilized) to export.
        rooms: dict[str, list[str]] = {}
        for rel in sorted(selected_rels):
            clip = clips_by_rel.get(rel)
            if not clip:
                continue
            room = clip.get("room") or (selects.get("clips", {}).get(rel, {}) or {}).get("room") or "unknown"
            p = clip.get("path")
            if not p:
                continue
            rooms.setdefault(room, []).append(p)

        # Target export folder under the run output.
        base_dir = ctx.export_pretrim_dir or (ctx.out_dir / "exports" / "pretrim")
        out_dir_by_room: dict[str, str] = {}
        for room in rooms.keys():
            out_dir_by_room[room] = str((base_dir / room).resolve())

        if not rooms:
            return AgentResult(name=self.name, ok=True, summary="No resolvable selected clip paths; nothing to export")

        script_path = ctx.va_dir / "resolve_export_pretrim_clips.py"
        payload = {
            "project_name": ctx.project_name,
            "rooms": rooms,
            "out_dir_by_room": out_dir_by_room,
            "render_preset": None,
            "render_format": None,
            "render_codec": None,
            "drx_path": str(ctx.grade_drx_path) if ctx.grade_drx_path else None,
            "grade_mode": int(ctx.grade_mode),
            "lut_path": ctx.grade_lut_path,
            "auto_grade": bool(ctx.auto_grade),
            "cdl": {
                "slope": ctx.cdl_slope,
                "offset": ctx.cdl_offset,
                "power": ctx.cdl_power,
                "saturation": ctx.cdl_saturation,
            },
        }
        _write_resolve_pretrim_export_script(script_path, payload)

        t0 = time.time()
        proc = subprocess.run([sys.executable, str(script_path)], capture_output=True, text=True)
        dt = time.time() - t0
        if proc.returncode != 0:
            return AgentResult(
                name=self.name,
                ok=False,
                summary=f"Resolve pretrim export script failed (exit={proc.returncode}).\n{proc.stderr.strip()}",
                artifacts={"pretrim_export_script": str(script_path)},
            )

        # Rename rendered files with a prefix and update index paths for selected rels.
        renamed = 0
        missing = 0
        for rel in sorted(selected_rels):
            clip = clips_by_rel.get(rel)
            if not clip:
                continue
            room = clip.get("room") or "unknown"
            room_dir = Path(out_dir_by_room.get(room, str(base_dir / room)))
            source_stem = Path(clip.get("name") or Path(clip.get("path") or "").name).stem
            rendered = _find_rendered_file(room_dir, source_stem)
            if not rendered:
                missing += 1
                continue

            prefix = _safe_prefix(ctx.export_pretrim_prefix, room=(room or "unknown").upper(), project=ctx.project_name)
            target = _unique_path(room_dir, f"{prefix}{source_stem}", rendered.suffix)
            try:
                if rendered.resolve() != target.resolve():
                    rendered.rename(target)
                clip["path"] = str(target)
                renamed += 1
            except Exception:
                # If rename fails (e.g., already exists), at least point index to rendered.
                clip["path"] = str(rendered)

        index["clips"] = clips
        index["pretrim_exported"] = True
        index["pretrim_exports_dir"] = str(base_dir)
        write_json(index_path, index)

        warnings: list[str] = []
        if proc.stderr.strip():
            warnings.append(proc.stderr.strip())
        if proc.stdout.strip():
            warnings.append(proc.stdout.strip())
        if missing:
            warnings.append(f"Missing pretrim exports for {missing} selected clips; kept previous paths for those.")

        ctx.artifacts["pretrim_exports_dir"] = base_dir
        ctx.artifacts["pretrim_export_script"] = script_path

        return AgentResult(
            name=self.name,
            ok=True,
            summary=f"Exported full selected graded clips before autotrim (updated_paths={renamed}, seconds={dt:.1f})",
            artifacts={
                "pretrim_exports_dir": str(base_dir),
                "pretrim_export_script": str(script_path),
                "stdout": proc.stdout.strip(),
            },
            warnings=warnings,
        )
