from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
import sys

from videoassistant.agents.base import AgentContext, AgentResult, read_json, write_json
from videoassistant.motion import quick_shakiness_score
from videoassistant.opencv_stabilize import OpenCVStabilizeSettings, stabilize_video_opencv


def _find_rendered_file(room_dir: Path, source_path: Path) -> Path | None:
    """Best-effort mapping from source clip to rendered stabilized file.

    Resolve's "Individual clips" render will usually keep the source clip name.
    We match by stem (case-insensitive) and pick the newest file.
    """

    if not room_dir.exists():
        return None
    stem = source_path.stem.lower()
    matches: list[Path] = []
    for p in room_dir.glob("*"):
        if not p.is_file():
            continue
        cand = p.stem.lower()
        if cand == stem or cand.startswith(stem) or (stem in cand):
            matches.append(p)
    if not matches:
        return None
    matches.sort(key=lambda x: x.stat().st_mtime, reverse=True)
    return matches[0]


def _write_resolve_stabilize_script(path: Path, payload: dict) -> None:
    payload_json = json.dumps(payload)
    script = """# Auto-generated by VideoAssistant
# Stabilize + Render (DaVinci Resolve scripting)
#
# Requirements:
# - DaVinci Resolve must be running (or launched with -nogui).
# - External Python must be able to import DaVinciResolveScript.

import json
import os
import sys
import time

PAYLOAD = json.loads(r'''__PAYLOAD_JSON__''')


def add_resolve_modules_to_syspath():
    candidates = []
    for env_key in ['RESOLVE_SCRIPTING_MODULES', 'RESOLVE_SCRIPT_API']:
        env = os.environ.get(env_key)
        if env:
            candidates.append(env)
    candidates.extend([
        r"C:\\ProgramData\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
        r"C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Support\\Developer\\Scripting\\Modules",
    ])
    for p in candidates:
        if p and os.path.isdir(p) and p not in sys.path:
            sys.path.insert(0, p)


def get_resolve():
    add_resolve_modules_to_syspath()
    try:
        import DaVinciResolveScript as dvr
    except Exception as e:
        raise SystemExit('Cannot import DaVinciResolveScript: ' + str(e))
    resolve = dvr.scriptapp('Resolve')
    if resolve is None:
        raise SystemExit('Resolve scripting app not available. Start Resolve and re-run.')
    return resolve


def find_timeline_by_name(proj, name: str):
    try:
        count = int(proj.GetTimelineCount())
    except Exception:
        return None
    for i in range(1, count + 1):
        tl = proj.GetTimelineByIndex(i)
        if tl and tl.GetName() == name:
            return tl
    return None


def ensure_unique_timeline(proj, media_pool, base_name: str):
    name = base_name
    i = 2
    while find_timeline_by_name(proj, name):
        name = f"{base_name}_{i}"
        i += 1
    try:
        tl = media_pool.CreateEmptyTimeline(name)
    except Exception:
        tl = None
    return tl or find_timeline_by_name(proj, name)


def ensure_project(pm, project_name: str):
    proj = pm.LoadProject(project_name)
    if proj:
        return proj
    try:
        cur = pm.GetCurrentProject()
    except Exception:
        cur = None
    if cur:
        return cur
    proj = pm.CreateProject(project_name)
    if not proj:
        raise SystemExit('Failed to create project: ' + project_name)
    return proj


def ensure_bin(media_pool, parent, name: str):
    for b in parent.GetSubFolderList() or []:
        if b.GetName() == name:
            return b
    return media_pool.AddSubFolder(parent, name)


def stabilize_timeline_items(timeline):
    # Stabilize all video items in track 1.
    items = []
    try:
        items = timeline.GetItemListInTrack('video', 1) or []
    except Exception:
        items = []
    ok_count = 0
    for it in items:
        try:
            if it.Stabilize():
                ok_count += 1
        except Exception:
            pass
    return ok_count, len(items)


def interactive_pause_before_stabilize(resolve, project, timeline, room: str):
    '''Pause to let user apply Stabilization attributes in the Resolve UI.

    Resolve's scripting API does not reliably expose Stabilizer Mode (Perspective/Similarity/Translation).
    The only reliable way to force Similarity/Translation is to set/paste clip attributes in the UI.
    '''

    try:
        project.SetCurrentTimeline(timeline)
    except Exception:
        pass
    try:
        resolve.OpenPage('edit')
    except Exception:
        pass

    print('--- Stabilization Settings (UI) ---')
    print('Room:', room)
    print('Open the timeline "' + (timeline.GetName() if timeline else '') + '" in Resolve.')
    print('1) Click the FIRST clip, Inspector > Stabilization > Mode = Similarity (or Translation).')
    print('2) Copy that clip.')
    print('3) Select ALL clips in the timeline, Paste Attributes... and enable Stabilization.')
    print('Then return here.')
    input('Press Enter to stabilize+render this room...')


def add_render_job_for_current_timeline(project, resolve, target_dir: str, render_preset: str | None, render_format: str | None, render_codec: str | None):
    resolve.OpenPage('deliver')

    if render_preset:
        try:
            project.LoadRenderPreset(render_preset)
        except Exception:
            pass

    def _pick_format_codec():
        # Prefer MP4 + H.265 for YouTube uploads; fall back to H.264; then fall back to whatever exists.
        try:
            formats = project.GetRenderFormats() or {}
        except Exception:
            formats = {}

        # Resolve returns format keys like "MP4", "MKV", "QuickTime".
        formats_lc = {str(k).lower(): k for k in formats.keys()}

        def pick_codec_for(fmt_key: str):
            try:
                codecs = project.GetRenderCodecs(fmt_key) or {}
            except Exception:
                codecs = {}
            # codecs is dict: description -> codecName
            def find(pred):
                for desc, name in codecs.items():
                    d = (desc or "").lower()
                    n = (name or "").lower()
                    if pred(d) or pred(n):
                        return name
                return None

            # Prefer NVIDIA encoders when available.
            c = find(lambda s: ("265" in s or "hevc" in s or "h.265" in s) and ("nvidia" in s))
            if c:
                return c
            c = find(lambda s: ("265" in s or "hevc" in s or "h.265" in s))
            if c:
                return c

            c = find(lambda s: ("264" in s or "avc" in s or "h.264" in s) and ("nvidia" in s))
            if c:
                return c
            c = find(lambda s: ("264" in s or "avc" in s or "h.264" in s))
            if c:
                return c
            # fall back to first codec name
            for _, name in codecs.items():
                return name
            return None

        for fmt_lc in ["mp4", "mkv", "quicktime"]:
            fmt_key = formats_lc.get(fmt_lc)
            if fmt_key:
                c = pick_codec_for(fmt_key)
                if c:
                    return fmt_key, c

        # any other format
        for fmt in formats.keys():
            c = pick_codec_for(fmt)
            if c:
                return fmt, c
        return None, None

    fmt = render_format
    cdc = render_codec
    if not (fmt and cdc):
        fmt, cdc = _pick_format_codec()
    if fmt and cdc:
        try:
            project.SetCurrentRenderFormatAndCodec(fmt, cdc)
        except Exception:
            pass

    # Individual clips
    try:
        project.SetCurrentRenderMode(0)
    except Exception:
        pass

    project.SetRenderSettings({
        'TargetDir': target_dir,
        'SelectAllFrames': 1,
    })
    return project.AddRenderJob()


def wait_for_render(project):
    while True:
        try:
            if not project.IsRenderingInProgress():
                return
        except Exception:
            return
        time.sleep(1)


def main():
    resolve = get_resolve()
    pm = resolve.GetProjectManager()
    project = ensure_project(pm, PAYLOAD['project_name'])
    media_pool = project.GetMediaPool()
    root_folder = media_pool.GetRootFolder()

    room_bins = {}
    for room in sorted(PAYLOAD['rooms'].keys()):
        room_bins[room] = ensure_bin(media_pool, root_folder, room)

    # Create per-room stabilization timelines.
    render_jobs = []
    for room in sorted(PAYLOAD['rooms'].keys()):
        clips = PAYLOAD['rooms'][room]
        if not clips:
            continue
        out_dir = PAYLOAD['out_dir_by_room'][room]
        os.makedirs(out_dir, exist_ok=True)

        media_pool.SetCurrentFolder(room_bins[room])
        items = []
        for clip_path in clips:
            imported = media_pool.ImportMedia([clip_path])
            if imported:
                items.append(imported[0])

        tl = ensure_unique_timeline(project, media_pool, room.upper() + '_STAB')
        if not tl:
            continue
        project.SetCurrentTimeline(tl)

        if items:
            try:
                media_pool.AppendToTimeline(items)
            except Exception:
                pass

        # Optional interactive pause to apply Similarity/Translation settings via Paste Attributes.
        if PAYLOAD.get('interactive'):
            interactive_pause_before_stabilize(resolve, project, tl, room)

        resolve.OpenPage('edit')
        ok_count, total = stabilize_timeline_items(tl)
        print(f"Room {room}: stabilized {ok_count}/{total} items")

        job_id = add_render_job_for_current_timeline(
            project,
            resolve,
            out_dir,
            PAYLOAD.get('render_preset'),
            PAYLOAD.get('render_format'),
            PAYLOAD.get('render_codec'),
        )
        if job_id:
            render_jobs.append(job_id)

    if not render_jobs:
        print('No render jobs created.')
        return

    # Render all queued jobs.
    project.StartRendering(render_jobs)
    wait_for_render(project)
    project.DeleteAllRenderJobs()
    try:
        pm.SaveProject()
    except Exception:
        pass
    print('Done. Stabilized and rendered per-room clips.')


if __name__ == '__main__':
    main()
"""

    script = script.replace("__PAYLOAD_JSON__", payload_json)

    path.write_text(script, encoding="utf-8")


@dataclass
class StabilizeAgent:
    name: str = "stabilize"

    def run(self, ctx: AgentContext) -> AgentResult:
        if not ctx.stabilize_first:
            return AgentResult(name=self.name, ok=True, summary="Skipped stabilization")

        idx_path = ctx.va_dir / "index.json"
        if not idx_path.exists():
            return AgentResult(name=self.name, ok=False, summary=f"Missing index: {idx_path}")

        stabilized_dir = ctx.stabilized_dir or (ctx.va_dir / "stabilized")
        stabilized_dir.mkdir(parents=True, exist_ok=True)

        # Backup raw index.
        raw_backup = ctx.va_dir / "index_raw.json"
        if not raw_backup.exists():
            raw_backup.write_text(idx_path.read_text(encoding="utf-8"), encoding="utf-8")

        idx = read_json(idx_path)
        clips = idx.get("clips", [])

        rooms: dict[str, list[str]] = {}
        out_dir_by_room: dict[str, str] = {}
        for clip in clips:
            room = clip.get("room") or "unknown"
            rooms.setdefault(room, []).append(clip["path"])
            room_dir = stabilized_dir / room
            out_dir_by_room[room] = str(room_dir)

        stabilize_script = ctx.va_dir / "resolve_stabilize_render.py"
        payload = {
            "project_name": ctx.project_name,
            "rooms": rooms,
            "out_dir_by_room": out_dir_by_room,
            "render_preset": ctx.stabilize_render_preset,
            "render_format": ctx.stabilize_render_format,
            "render_codec": ctx.stabilize_render_codec,
            "interactive": bool(getattr(ctx, 'stabilize_interactive', False)),
        }
        _write_resolve_stabilize_script(stabilize_script, payload)

        # Run Resolve script using the same interpreter running the assistant.
        # Resolve must already be running and have scripting enabled.
        import subprocess

        t0 = time.time()
        if getattr(ctx, 'stabilize_interactive', False):
            # In interactive mode, inherit the terminal stdio so input() prompts work.
            proc = subprocess.run([sys.executable, str(stabilize_script)], text=True)
        else:
            proc = subprocess.run([sys.executable, str(stabilize_script)], capture_output=True, text=True)
        dt = time.time() - t0
        warnings: list[str] = []
        if proc.returncode != 0:
            return AgentResult(
                name=self.name,
                ok=False,
                summary=f"Resolve stabilization script failed (exit={proc.returncode}).\n{proc.stderr.strip()}",
                artifacts={"stabilize_script": str(stabilize_script)},
            )

        # Only available when capture_output=True.
        if getattr(proc, 'stderr', None) and proc.stderr and proc.stderr.strip():
            warnings.append(proc.stderr.strip())
        if getattr(proc, 'stdout', None) and proc.stdout and proc.stdout.strip():
            warnings.append(proc.stdout.strip())

        # Update index.json paths to stabilized renders.
        updated = 0
        missing = 0
        for clip in clips:
            src = Path(clip["path"])
            room = clip.get("room") or "unknown"
            rendered = _find_rendered_file(stabilized_dir / room, src)
            if rendered:
                clip["path"] = str(rendered)
                updated += 1
            else:
                missing += 1

        idx["clips"] = clips
        idx["stabilized"] = True
        idx["stabilized_dir"] = str(stabilized_dir)
        write_json(idx_path, idx)

        # Stabilization QC: compare a quick shakiness score between original and stabilized.
        qc_enabled = bool(getattr(ctx, 'stabilize_qc', True))
        qc_path = ctx.va_dir / 'stabilization_qc.json'
        regressions = []
        qc = {
            'sample_fps': float(getattr(ctx, 'stabilize_qc_sample_fps', 3.0)),
            'scale_width': int(getattr(ctx, 'stabilize_qc_scale_width', 256)),
            'max_frames': int(getattr(ctx, 'stabilize_qc_max_frames', 96)),
            'regression_ratio': float(getattr(ctx, 'stabilize_qc_regression_ratio', 1.15)),
            'clips': {},
        }
        if qc_enabled and raw_backup.exists():
            try:
                raw_idx = read_json(raw_backup)
                raw_by_rel = {c.get('rel'): c for c in (raw_idx.get('clips') or []) if c.get('rel')}
            except Exception:
                raw_by_rel = {}

            clip_by_rel = {c.get('rel'): c for c in clips if c.get('rel')}

            for clip in clips:
                rel = clip.get('rel')
                raw_clip = raw_by_rel.get(rel) if rel else None
                raw_path = Path(raw_clip['path']) if (raw_clip and raw_clip.get('path')) else None
                stab_path = Path(clip['path']) if clip.get('path') else None
                if not (raw_path and stab_path and raw_path.exists() and stab_path.exists()):
                    continue

                raw_score, raw_meta = quick_shakiness_score(
                    raw_path,
                    sample_fps=qc['sample_fps'],
                    scale_width=qc['scale_width'],
                    max_frames=qc['max_frames'],
                )
                stab_score, stab_meta = quick_shakiness_score(
                    stab_path,
                    sample_fps=qc['sample_fps'],
                    scale_width=qc['scale_width'],
                    max_frames=qc['max_frames'],
                )
                qc['clips'][rel or str(raw_path)] = {
                    'raw_path': str(raw_path),
                    'stabilized_path': str(stab_path),
                    'raw_score': raw_score,
                    'stabilized_score': stab_score,
                    'raw_meta': raw_meta,
                    'stabilized_meta': stab_meta,
                }

                if raw_score is None or stab_score is None or raw_score <= 0:
                    continue
                ratio = float(stab_score / raw_score)
                if ratio >= float(qc['regression_ratio']):
                    regressions.append({'rel': rel, 'ratio': ratio, 'raw_score': raw_score, 'stabilized_score': stab_score})

            # Optional: OpenCV fallback for regressed clips (non-interactive).
            opencv_fallbacks: list[dict] = []
            if regressions and bool(getattr(ctx, 'stabilize_opencv_fallback', False)):
                qc['regressions_resolve'] = list(regressions)
                fallback_dir = stabilized_dir.parent / f"{stabilized_dir.name}_cv"
                fallback_dir.mkdir(parents=True, exist_ok=True)

                ocv_settings = OpenCVStabilizeSettings(
                    mode=str(getattr(ctx, 'opencv_mode', 'translation')),
                    smooth_seconds=float(getattr(ctx, 'opencv_smooth_seconds', 0.5)),
                    zoom=float(getattr(ctx, 'opencv_zoom', 1.06)),
                )

                for r in regressions:
                    rel = r.get('rel')
                    if not rel:
                        continue
                    raw_clip = raw_by_rel.get(rel)
                    stab_clip = clip_by_rel.get(rel)
                    if not (raw_clip and stab_clip):
                        continue
                    raw_path = Path(raw_clip.get('path') or '')
                    if not raw_path.exists():
                        continue

                    room = stab_clip.get('room') or raw_clip.get('room') or 'unknown'
                    out_room_dir = fallback_dir / str(room)
                    out_room_dir.mkdir(parents=True, exist_ok=True)
                    out_path = out_room_dir / f"{raw_path.stem}_cv_{ocv_settings.mode}.mp4"

                    try:
                        meta = stabilize_video_opencv(raw_path, out_path, ocv_settings)
                        stab_clip['path'] = str(out_path)
                        opencv_score, opencv_meta = quick_shakiness_score(
                            out_path,
                            sample_fps=qc['sample_fps'],
                            scale_width=qc['scale_width'],
                            max_frames=qc['max_frames'],
                        )

                        entry = qc['clips'].get(rel)
                        if isinstance(entry, dict):
                            entry['opencv_path'] = str(out_path)
                            entry['opencv_meta'] = {**meta, **(opencv_meta or {})}
                            entry['opencv_score'] = opencv_score
                            if (entry.get('raw_score') is not None) and (opencv_score is not None) and float(entry['raw_score']) > 0:
                                entry['opencv_ratio'] = float(opencv_score) / float(entry['raw_score'])

                        opencv_fallbacks.append(
                            {
                                'rel': rel,
                                'room': room,
                                'raw_path': str(raw_path),
                                'opencv_path': str(out_path),
                                'opencv_score': opencv_score,
                            }
                        )
                    except Exception as e:
                        warnings.append(f"OpenCV fallback failed for {rel}: {e}")

                if opencv_fallbacks:
                    qc['opencv_fallbacks'] = opencv_fallbacks
                    qc['opencv_fallback_dir'] = str(fallback_dir)
                    ctx.artifacts['stabilized_cv_dir'] = fallback_dir

                    # Recompute regressions list based on the *effective* stabilized paths (after fallback).
                    regressions_after = []
                    for clip in clips:
                        rel = clip.get('rel')
                        raw_clip = raw_by_rel.get(rel) if rel else None
                        raw_path = Path(raw_clip['path']) if (raw_clip and raw_clip.get('path')) else None
                        eff_path = Path(clip['path']) if clip.get('path') else None
                        if not (rel and raw_path and eff_path and raw_path.exists() and eff_path.exists()):
                            continue
                        raw_score = qc['clips'].get(rel, {}).get('raw_score')
                        if raw_score is None or float(raw_score) <= 0:
                            continue
                        eff_score, _eff_meta = quick_shakiness_score(
                            eff_path,
                            sample_fps=qc['sample_fps'],
                            scale_width=qc['scale_width'],
                            max_frames=qc['max_frames'],
                        )
                        if eff_score is None:
                            continue
                        ratio = float(eff_score) / float(raw_score)
                        if ratio >= float(qc['regression_ratio']):
                            regressions_after.append(
                                {
                                    'rel': rel,
                                    'ratio': ratio,
                                    'raw_score': raw_score,
                                    'effective_score': eff_score,
                                    'effective_path': str(eff_path),
                                }
                            )
                    regressions_after.sort(key=lambda rr: rr.get('ratio', 0), reverse=True)
                    qc['regressions_after_fallback'] = regressions_after
                    regressions = regressions_after

                    # Persist the updated index so downstream analysis uses fallback outputs.
                    idx['clips'] = clips
                    write_json(idx_path, idx)

            regressions.sort(key=lambda r: r.get('ratio', 0), reverse=True)
            qc['regressions'] = regressions
            write_json(qc_path, qc)
            ctx.artifacts['stabilization_qc'] = qc_path

            if regressions:
                top = regressions[:10]
                warnings.append(
                    'Stabilization QC: some clips got shakier after stabilization (likely Perspective warping). '
                    'See stabilization_qc.json; consider re-stabilizing those with Similarity/Translation. '
                    + 'Top: ' + ', '.join([str(r.get('rel')) for r in top if r.get('rel')])
                )

        if missing:
            warnings.append(f"Missing stabilized renders for {missing} clips; kept original paths for those.")

        # Always remind about Resolve mode limitation when stabilization is enabled.
        mode_hint = getattr(ctx, 'stabilize_mode_hint', None)
        warnings.append(
            'Resolve stabilization mode is controlled in the UI (Inspector > Stabilization > Mode); '
            + (f"current run hint='{mode_hint}'. " if mode_hint else '')
            + 'Resolve scripting does not expose per-clip mode switching reliably.'
        )

        ctx.artifacts["stabilized_dir"] = stabilized_dir
        ctx.artifacts["stabilize_script"] = stabilize_script
        return AgentResult(
            name=self.name,
            ok=True,
            summary=f"Stabilized and rendered clips (updated={updated}, seconds={dt:.1f})",
            artifacts={
                "stabilize_script": str(stabilize_script),
                "stabilized_dir": str(stabilized_dir),
                **({"stdout": proc.stdout.strip()} if getattr(proc, 'stdout', None) else {}),
                **({"stabilization_qc": str(qc_path)} if qc_enabled and qc_path.exists() else {}),
            },
            warnings=warnings,
        )
